# Generated by Django 4.1.5 on 2023-02-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='user_type',
            field=models.CharField(choices=[('AUTHOR', 'author'), ('REVIEWER', 'reviewer'), ('EDITOR', 'editor'), ('PUBLISHER', 'publisher')], default='author', max_length=64),
        ),
    ]
