# Generated by Django 4.1.5 on 2023-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profiles_publications_and_more'),
        ('articles', '0002_alter_article_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewer',
            field=models.ManyToManyField(to='profiles.profiles'),
        ),
    ]
