# Generated by Django 4.1.5 on 2023-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='reviewer_publication',
            name='scope',
        ),
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(to='articles.subject'),
        ),
        migrations.AddField(
            model_name='reviewer_publication',
            name='scope',
            field=models.ManyToManyField(to='articles.subject'),
        ),
    ]
