# Generated by Django 4.1.5 on 2023-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Unsubmitted', 'Unsubmitted'), ('Pre Review', 'Pre Review'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Typesetting', 'Typesetting'), ('Pre Publication', 'Pre Publication'), ('Published', 'Published')], default='Unsubmitted', max_length=15, null=True),
        ),
    ]
