# Generated by Django 4.1.5 on 2023-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='from_page',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='notes_to_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='to_page',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
