# Generated by Django 4.1.5 on 2023-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_reviewer_publication_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='Null title', verbose_name='Arabic Title'),
        ),
    ]
