# Generated by Django 4.1.5 on 2023-02-28 11:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('ar_en', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('received_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Under Review', 'Peer Review'), ('Under Revision', 'Revision'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Typesetting', 'Typesetting'), ('pre_publication', 'Pre Publication'), ('Published', 'Published')], default='Unsubmitted', max_length=15)),
                ('volume', models.SmallIntegerField(blank=True, null=True)),
                ('issue', models.SmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_editor_decision', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('en_abstract', models.TextField(blank=True, null=True)),
                ('en_keyword', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('file_link', models.TextField(blank=True, null=True)),
                ('num_references', models.IntegerField(blank=True, null=True)),
                ('latest_reference', models.IntegerField(blank=True, null=True)),
                ('oldest_reference', models.IntegerField(blank=True, null=True)),
                ('meadian_reference', models.FloatField(blank=True, null=True)),
                ('avg_recent_references', models.FloatField(blank=True, null=True)),
                ('ref_mention_count', models.IntegerField(blank=True, null=True)),
                ('num_figurs', models.IntegerField(blank=True, null=True)),
                ('num_tables', models.IntegerField(blank=True, null=True)),
                ('num_charts', models.IntegerField(blank=True, null=True)),
                ('num_authors', models.IntegerField(blank=True, null=True)),
                ('num_publication', models.IntegerField(blank=True, null=True)),
                ('paper_len', models.FloatField(blank=True, null=True)),
                ('ar_word_count', models.FloatField(blank=True, null=True)),
                ('en_word_count', models.FloatField(blank=True, null=True)),
                ('ar_word_avg', models.FloatField(blank=True, null=True)),
                ('en_word_avg', models.FloatField(blank=True, null=True)),
                ('num_sentences', models.FloatField(blank=True, null=True)),
                ('avg_words_per_sentence', models.FloatField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('agricultural_economics', 'agricultural economics'), ('agriculture_biotechnology', 'agriculture biotechnology'), ('crop_production', 'crop production'), ('environmental_siences', 'environmental siences'), ('food_technology', 'food technology'), ('horticulture', 'horticulture'), ('livestock_production', 'livestock production'), ('natural_resources', 'natural resources'), ('plant_protection', 'plant protection')], default='null', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
