# Generated by Django 4.1.5 on 2023-03-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Unsubmitted', 'Unsubmitted'), ('Under Review', 'Under Review'), ('Under Revision', 'Under Revision'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Typesetting', 'Typesetting'), ('Pre Publication', 'Pre Publication'), ('Published', 'Published')], default='Unsubmitted', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Reviewer_publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_current_reviews', models.IntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('agricultural_economics', 'agricultural economics'), ('agriculture_biotechnology', 'agriculture biotechnology'), ('crop_production', 'crop production'), ('environmental_siences', 'environmental siences'), ('food_technology', 'food technology'), ('horticulture', 'horticulture'), ('livestock_production', 'livestock production'), ('natural_resources', 'natural resources'), ('plant_protection', 'plant protection')], default='null', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
