# Generated by Django 4.1.5 on 2023-03-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profiles_user_type'),
        ('articles', '0006_remove_article_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviewer',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.profiles'),
        ),
    ]
