# Generated by Django 4.1.5 on 2023-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_ar_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='file_link'),
        ),
    ]
