# Generated by Django 4.1.5 on 2023-06-22 20:25

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0016_alter_article_file_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_directory', models.FileField(max_length=500, upload_to=articles.models.facility_path)),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
