# Generated by Django 4.1.5 on 2023-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_article_file_link_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file_link'),
        ),
        migrations.AlterField(
            model_name='article_files',
            name='file_directory',
            field=models.FileField(max_length=500, upload_to='documents/None'),
        ),
    ]
