# Generated by Django 4.1.5 on 2023-06-24 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_file_link_alter_article_files_file_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='copyright_file_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Copyright File'),
        ),
        migrations.AddField(
            model_name='article',
            name='en_title',
            field=models.TextField(blank=True, null=True, verbose_name='English Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='no_author_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Manuscript File without Authors'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Arabic Abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ar_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='article',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Unsubmitted', 'Unsubmitted'), ('Pre Review', 'Pre Review'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Typesetting', 'Typesetting'), ('Pre Publication', 'Pre Publication'), ('Published', 'Published')], default='Unsubmitted', max_length=15, null=True, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_editor_decision',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Editorial Decision'),
        ),
        migrations.AlterField(
            model_name='article',
            name='en_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='English Abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='en_keyword',
            field=models.TextField(blank=True, null=True, verbose_name='English Keyword'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Manuscript File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words',
            field=models.TextField(blank=True, null=True, verbose_name='Arabic Keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='received_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='article',
            name='result',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Arabic Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
