# Generated by Django 4.1.5 on 2023-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_article_files_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E.mail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='from_page',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='From Page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes_to_author',
            field=models.TextField(blank=True, null=True, verbose_name='Notes to Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='to_page',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='To Page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
