# Generated by Django 4.1.5 on 2023-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_author_order_email_alter_article_from_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revised_pdf_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Revised PDF'),
        ),
    ]
