# Generated by Django 4.1.5 on 2023-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_article_revised_pdf_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer_publication',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='reviewer_publication',
            name='num_current_reviews',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Current Reviews'),
        ),
    ]
