# Generated by Django 4.1.5 on 2023-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='arabic_name')),
                ('english_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='english_name')),
                ('job_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='job_title')),
                ('specification', models.CharField(blank=True, max_length=250, null=True, verbose_name='specification')),
                ('work_address', models.TextField(blank=True, null=True, verbose_name='work_address')),
            ],
        ),
    ]
