# Generated by Django 4.1.5 on 2023-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial_board',
            name='en_specification',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='en_specification'),
        ),
        migrations.AddField(
            model_name='editorial_board',
            name='en_work_address',
            field=models.TextField(blank=True, null=True, verbose_name='en_work_address'),
        ),
    ]
