# Generated by Django 4.1.5 on 2023-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_editorial_board_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(blank=True, max_length=250, null=True, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
        migrations.AlterField(
            model_name='editorial_board',
            name='job_title',
            field=models.CharField(blank=True, choices=[('رئيس_التحرير', 'رئيس التحرير'), ('رئيس_التحرير_المشارك', 'رئيس التحرير المشارك'), ('أمين_سر_المجلة', 'أمين سر المجلة'), ('التحليل_الإحصائي', 'التحليل الإحصائي'), ('مشرف_الموقع', 'مشرف الموقع'), ('مدقق_لغة_انكليزي', 'مدقق لغة انكليزي'), ('مدقق_لغة_عربي', 'مدقق لغة عربي'), ('هيئة_التحرير_الدولية', 'هيئة التحرير الدولية'), ('هيئة_التحرير_المحلية', 'هيئة التحرير المحلية'), ('المحكمين_الدوليين', 'المحكمين الدوليين'), ('المحكمين_المحليين', 'المحكمين المحليين')], max_length=250, null=True, verbose_name='job_title'),
        ),
    ]
