# Generated by Django 4.1.5 on 2023-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_editorial_board_en_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial_board',
            name='job_title',
            field=models.CharField(blank=True, choices=[('رئيس_التحرير', 'Editor in Chief'), ('رئيس_التحرير_المشارك', 'Co-editor in Chief'), ('أمين_سر_المجلة', 'Secretary of Journal'), ('التحليل_الإحصائي', 'Statistical analysis'), ('مشرف_الموقع', 'Journal Website Supervisor'), ('مدقق_لغة_انكليزي', 'English Language Proofreading'), ('مدقق_لغة_عربي', 'Arabic Language Proofreading'), ('هيئة_التحرير_الدولية', 'International Editorial Board'), ('هيئة_التحرير_المحلية', 'National Editorial Board'), ('المحكمين_الدوليين', 'International Reviewers'), ('المحكمين_المحليين', 'National Reviewers')], max_length=250, null=True, verbose_name='job_title'),
        ),
    ]
