# Generated by Django 4.1.5 on 2023-03-29 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0011_alter_article_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('invited', models.BooleanField(default=False)),
                ('invited_at', models.DateField(blank=True, null=True)),
                ('invitation_expire_on', models.DateField(blank=True, null=True)),
                ('replay', models.CharField(blank=True, choices=[('ACCEPT', 'accept invitation'), ('REJECT', 'reject invitaion')], max_length=225, null=True)),
                ('review_start_on', models.DateField(blank=True, null=True)),
                ('review_ends_on', models.DateField(blank=True, null=True)),
                ('notes_to_editor', models.TextField(blank=True, null=True)),
                ('notes_to_author', models.TextField(blank=True, null=True)),
                ('q1', models.SmallIntegerField(blank=True, null=True)),
                ('q1_note', models.TextField(blank=True, null=True)),
                ('q2', models.SmallIntegerField(blank=True, null=True)),
                ('q2_note', models.TextField(blank=True, null=True)),
                ('q3', models.SmallIntegerField(blank=True, null=True)),
                ('q3_note', models.TextField(blank=True, null=True)),
                ('q4', models.SmallIntegerField(blank=True, null=True)),
                ('q4_note', models.TextField(blank=True, null=True)),
                ('q5', models.SmallIntegerField(blank=True, null=True)),
                ('q5_note', models.TextField(blank=True, null=True)),
                ('q6', models.SmallIntegerField(blank=True, null=True)),
                ('q6_note', models.TextField(blank=True, null=True)),
                ('q7', models.SmallIntegerField(blank=True, null=True)),
                ('q7_note', models.TextField(blank=True, null=True)),
                ('q8', models.SmallIntegerField(blank=True, null=True)),
                ('q8_note', models.TextField(blank=True, null=True)),
                ('q9', models.SmallIntegerField(blank=True, null=True)),
                ('q9_note', models.TextField(blank=True, null=True)),
                ('q10', models.SmallIntegerField(blank=True, null=True)),
                ('q10_note', models.TextField(blank=True, null=True)),
                ('q11', models.SmallIntegerField(blank=True, null=True)),
                ('q11_note', models.TextField(blank=True, null=True)),
                ('q12', models.SmallIntegerField(blank=True, null=True)),
                ('q12_note', models.TextField(blank=True, null=True)),
                ('q13', models.SmallIntegerField(blank=True, null=True)),
                ('q13_note', models.TextField(blank=True, null=True)),
                ('q14', models.SmallIntegerField(blank=True, null=True)),
                ('q14_note', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
