# Generated by Django 4.1.5 on 2023-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdetailes',
            name='order',
        ),
        migrations.AddField(
            model_name='reviewdetailes',
            name='approval',
            field=models.CharField(blank=True, choices=[('approve', 'Approve this article after complying with suggested amendments and comments, without return.'), ('reject', 'Reject this article and send it back to the author for the following reasons:'), ('approve_with_return', 'Return the article to the author to make the required modifications, then return it to me again.')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q10',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q10_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q11',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q11_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q12',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q12_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q13',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q13_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q14',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q14_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q1_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q2_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q3_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q4_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q5_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q6',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q6_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q7',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q7_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q8',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q8_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q9',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='q9_note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
