# Generated by Django 4.1.5 on 2023-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewdetailes_done_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetailes',
            name='approval',
            field=models.CharField(blank=True, choices=[('approve', 'Approve this article after complying with suggested amendments and comments, without return.'), ('reject', 'Reject this article and send it back to the author for the following reasons:'), ('approve_with_return', 'Return the article to the author to make the required modifications, then return it to me again.')], max_length=225, null=True, verbose_name='approval'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='done_review',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='done_review'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='invitation_expire_on',
            field=models.DateField(blank=True, null=True, verbose_name='invitation_expire_on'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='invited',
            field=models.BooleanField(default=False, verbose_name='invited'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='invited_at',
            field=models.DateField(blank=True, null=True, verbose_name='invited_at'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last_update'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='notes_to_author',
            field=models.TextField(blank=True, null=True, verbose_name='notes_to_author'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='notes_to_editor',
            field=models.TextField(blank=True, null=True, verbose_name='notes_to_editor'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='replay',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'accept invitation'), ('REJECT', 'reject invitaion')], max_length=225, null=True, verbose_name='replay'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='review_ends_on',
            field=models.DateField(blank=True, null=True, verbose_name='review_ends_on'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='review_start_on',
            field=models.DateField(blank=True, null=True, verbose_name='review_start_on'),
        ),
        migrations.AlterField(
            model_name='reviewdetailes',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='score'),
        ),
    ]
