# Generated by Django 4.1.5 on 2023-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('REVIEWER', 'REVIEWER'), ('EDITOR', 'EDITOR'), ('PUBLISHER', 'PUBLISHER')], default='author', max_length=64),
        ),
    ]
