# Generated by Django 4.1.5 on 2023-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profiles_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='certificate',
            field=models.CharField(blank=True, help_text='الدكتور, المهندس ...', max_length=15, null=True, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='specialist',
            field=models.CharField(blank=True, help_text='اقتصاد زراعي, محاصيل, موارد طبيعية ...', max_length=255, null=True, verbose_name='Specialist'),
        ),
    ]
