# Generated by Django 4.1.5 on 2023-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profiles_certificate_alter_profiles_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='certificate',
            field=models.CharField(blank=True, help_text='الدكتور, المهندس ...', max_length=15, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email2',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='email2'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone2'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='publications_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='publications_count'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='specialist',
            field=models.CharField(blank=True, help_text='اقتصاد زراعي, محاصيل, موارد طبيعية ...', max_length=255, null=True, verbose_name='specialist'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='specific_specialist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='specific_specialist'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('REVIEWER', 'REVIEWER'), ('EDITOR', 'EDITOR'), ('PUBLISHER', 'PUBLISHER')], default='AUTHOR', max_length=64, verbose_name='user_type'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='work_address',
            field=models.TextField(blank=True, null=True, verbose_name='work_address'),
        ),
    ]
