# Generated by Django 4.1.5 on 2023-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profiles_address_alter_profiles_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='en_certificate',
            field=models.CharField(blank=True, help_text='PhD, Eng ...', max_length=15, null=True, verbose_name='English Certificate'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='en_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='en_work_address',
            field=models.TextField(blank=True, null=True, verbose_name='English Work Address'),
        ),
    ]
